name 'ha_certs'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ha_certs'
long_description 'Installs/Configures ha_certs'
version '0.1.0'